#!/usr/bin/env ruby

require 'rubygems'
require 'net/scp'
require 'open-uri'
require 'colorize'
require "safe_yaml/load"
require 'highline/import'
require 'thor'

class Aka < Thor
  include Thor::Actions

  check_unknown_options!

end

Aka.start(ARGV)
