#!/usr/bin/env ruby
require 'rubygems'
require 'net/scp'
require 'open-uri'
require 'colorize'
require "safe_yaml/load"
require 'highline/import'
require 'thor'

class Aka < Thor
  include Thor::Actions
  check_unknown_options!
  package_name "aka"

  #
  # TADA
  #
  desc "tada [name]", "generate an alias"
  method_options :last => :boolean,
                :something => :boolean,
                :somethignelse => :boolean,
                :alias => :t
  def tada args
    if yes? "how are you? (yN)"
      puts "ok"
    else
      puts "no"
    end
  end

  #
  # GENERATE
  #
  desc "generate [name]", "generate an alias"
  method_options :last => :boolean, :alias => :g
  def generate args
    result = false
    if options.last?
      result = add(add_last_command(parseARGS(args))) if args
    else
      result = add(parseARGS(args)) if args
      if options.proj? and result == true
        FileUtils.touch("#{Dir.pwd}/.aka")
        add_to_proj(args)
      end
    end
    reload_dot_file if result == true and !options.noreload
  end


  #
  # DESTROY
  #
  desc "destroy [name]", "destroy an alias"
  method_options :force => :boolean, :alias => :d
  def destroy args
    result = remove(args) if args
    unalias_the(args) if !options.nounalias and result == true and args
    reload_dot_file if result == true and !options.noreload
  end


  #
  # FIND
  #
  desc "find [name]", "find an alias"
  method_options :force => :boolean, :alias => :f
  def find

  end

  #
  # EDIT
  #
  desc "edit [name]", "edit an alias"
  method_options :force => :boolean, :alias => :e
  def edit

  end

  desc "list [name]", "list alias"
  method_options :force => :boolean, :alias => :l
  def list

  end

  #
  # INSTALL
  #
  desc "install [name]", "install aka"
  method_options :force => :boolean
  def install

  end

  #
  # INIT
  #
  desc "init", "initiate aka"
  def init

  end

  #
  # PRIVATE METHODS
  #

  private

  def setPath(path, value)
    data = readYML("#{Dir.home}/.aka/.config")
    if data.has_key?(value) == true
      old_path = data[value]
      data[value] = path
      writeYML("#{Dir.home}/.aka/.config", data)
      puts "data[#{value}] has #{old_path} changed to #{path}"
    else
      puts "error: --#{value} does not exist in #{Dir.home}/.aka/.config "
    end
  end

  def reload
    system "source #{readYML("#{Dir.home}/.aka/.config")["location"]}"
  end

  def readYML path
    return YAML.load_file(path)
  end

  def writeYML path, theyml
    File.open(path, 'w') {|f| f.write theyml.to_yaml } #Store
  end

  def write_with array
    File.open(readYML("#{Dir.home}/.aka/.config")["location"], 'w') { |file|
      array.each do |line|
        file.write(line)
      end
    }
  end

  def write_with_newline array
    File.open(readYML("#{Dir.home}/.aka/.config")["location"], 'w') { |file|
      array.each do |line|
        file.write(line + "\n")
      end
    }
  end

  def write str, path
    File.open(path, 'w') { |file| file.write(str) }
  end

  def append str, path
    File.open(path, 'a') { |file| file.write(str) }
  end

  def append_with_newline str, path
    File.open(path, 'a') { |file| file.write(str + "\n") }
  end

  def reload_dot_file
   system("kill -SIGUSR1 #{Process.ppid}")
  end

  def historywrite
    system "kill -SIGUSR2 #{Process.ppid}"
  end

  def unalias_the value
    system "echo '#{value}' > ~/sigusr1-args;"
    system "kill -SIGUSR2 #{Process.ppid}"
  end

  def split_domain_user fulldomain
    username = fulldomain.split("@").first
    domain = fulldomain.split("@")[1]
    return [username, domain]
  end

  def split fulldomain
    username = fulldomain.split("@").first
    domain = fulldomain.split("@")[1].split(":").first
    port = fulldomain.split("@")[1].split(":")[1]
    return [username, domain, port]
  end

  def add input
    if input and show_alias(input).first == false and not_empty_alias(input) == false
      array = input.split("=")
      full_command = "alias #{array.first}='#{array[1]}'".gsub("\n","") #remove new line in command
      print_out_command = "aka g #{array.first}='#{array[1]}'"
      File.open(readYML("#{Dir.home}/.aka/.config")["location"], 'a') { |file| file.write("\n" +full_command) }
      puts "    #{print_out_command} is added to #{readYML("#{Dir.home}/.aka/.config")["location"]}"
      return true
    else
      puts "The alias is already present."
      return false
    end
  end

  def not_empty_alias input
    array = input.split("=")
    return true if array.count < 2
    return array[1].strip == ""
  end

  def show_alias argument
    if content = File.open(readYML("#{Dir.home}/.aka/.config")["location"]).read
      content.gsub!(/\r\n?/, "\n")
      content_array = content.split("\n")
      content_array.each_with_index { |line, index|
        value = line.split(" ")
        if value.length > 1 and value.first == "alias"
          answer = value[1].split("=")
          if found?(answer.first, argument.split("=").first, line) == true
            return [true, answer.first, answer[1]]
          end
        end
      }
    else
      puts "#{@pwd} cannot be found.".red
      return [false, nil, nil]
    end
    return [false, nil, nil]
  end

  # def show argument
  #   if content = File.open(readYML("#{Dir.home}/.aka/.config")["location"]).read
  #     content.gsub!(/\r\n?/, "\n")
  #     content_array = content.split("\n")
  #     content_array.each_with_index { |line, index|
  #       value = line.split(" ")
  #       if value.length > 1 and value.first == "alias"
  #         answer = value[1].split("=")
  #         if found?(answer.first, argument, line)
  #           return true
  #         end
  #       end
  #     }
  #   else
  #     puts "#{@pwd} cannot be found.".red
  #     return false
  #   end
  #   puts "No alias is found.".red
  #   return false
  # end

  def remove input
    if content=File.open(readYML("#{Dir.home}/.aka/.config")["location"]).read
      content.gsub!(/\r\n?/, "\n")
      content_array= content.split("\n")
      content_array.each_with_index { |line, index|
        value = line.split(" ")
        if value.length > 1 and value.first == "alias"
          answer = value[1].split("=")
          if answer.first == input
            content_array.delete_at(index) and write_with_newline(content_array)
            puts "    #{line} is removed from #{Dir.home}/.bash_profile".red
            return true
          end
        end
      }
    else
      puts "#{@pwd} cannot be found.".red
      return false
    end
  end

  # def find input
  #   if input == nil
  #     puts "Press q to cancel. or press ctrl+z to stop".red
  #     input = ask "Which alias to find: (q to quit)"
  #     if input == "q"
  #       puts "Exit." and exit()
  #     end
  #   end
  #
  #   founded = false
  #   if content=File.open(readYML("#{Dir.home}/.aka/.config")["location"]).read
  #     content.gsub!(/\r\n?/, "\n")
  #     content_array = content.split("\n")
  #     content_array.each_with_index { |line, index|
  #       value = line.split(" ")
  #       if value.length > 1 and value.first == "alias"
  #         answer = value[1].split("=")
  #         if found?(answer.first, input, line) == true
  #           founded = true
  #         end
  #       end
  #     }
  #     puts "nothing is found." if founded == false
  #   end
  # end

  # def record method, command
  #   record = method + "," + command + "," + Time.now.to_s
  #   append(record,".history")
  # end

  def history
    if content = File.open(bash_history_path).read
      puts ".bash_history is available"
      count=0
      content.gsub!(/\r\n?/, "\n")
      content_array = content.split("\n")
      content_array.each_with_index { |line, index|
        array = line.split(" ")
        if array.first == "alias"
          count += 1
        end
        puts "#{index+1} #{line}"
      }
      puts "There are #{count} histories"
    else
      puts ".bash_history is not available".red
    end
  end

  def version
    puts ""
    puts "aka #{program(:version)} - #{program(:last_update)}"
    puts "#{program(:author)} - #{program(:contact)}"
    puts "https://github.com/ytbryan/aka"
  end

  def found? answer, argument, line
    if answer == argument
      # puts line.red + " - aka add #{argument}"
      puts line.red
      return true
    else
      return false
    end
  end

  # def update
  #   system("sudo rm -rf /usr/local/bin/aka; curl -o /usr/local/bin/aka https://raw.githubusercontent.com/ytbryan/aka/master/cmd/aka; chmod 755 /usr/local/bin/aka") #download the ruby file into _plugins
  # end

  def edit newcommand, this_alias
    return append("alias " + this_alias + "='" + newcommand + "'", readYML("#{Dir.home}/.aka/.config")["location"] )
  end

  def edit_alias newalias, thiscommand
    return append("alias " + newalias + "='" + thiscommand + "'", readYML("#{Dir.home}/.aka/.config")["location"] )
  end

  def count
    alias_count = 0
    if content=File.open(readYML("#{Dir.home}/.aka/.config")["location"]).read
      content.gsub!(/\r\n?/, "\n")
      content_array= content.split("\n")
      content_array.each_with_index { |line, index|
        value = line.split(" ")
        if value.length > 1 and value.first == "alias"
          answer = value[1].split("=")
          alias_count += 1
        end
      }
      return alias_count
    end
  end

  def setup
    input = ask "- Do you wish to expand your bash history? (y/N)"
    if input == 'y'
      append("export HISTSIZE=10000","/etc/profile")
    end

    input = ask "- Do you wish to setup auto-reloading of your dot file <#{readYML("#{Dir.home}/.aka/.config")["location"]}>? (y/N)"
    if input == 'y'
      trap = "sigusr2() { unalias $1;}
      sigusr1() { source #{readYML("#{Dir.home}/.aka/.config")["location"]}; history -a; echo 'reloaded dot file'; }
      trap sigusr1 SIGUSR1
      trap 'sigusr2 $(cat ~/sigusr1-args)' SIGUSR2\n".pretty
      append(trap, readYML("#{Dir.home}/.aka/.config")['location'])
    end

    puts "Done. Please restart this shell.".red
  end

  def write_to_location location, address
    if aka_directory_exists?
      write(location, address)
    else
      puts ".aka not found.".red
    end
  end

  def read location
    answer = dot_location_exists?(location)
    if answer == true and content = File.open(location).read
      return content
    end
    return ""
  end

  def dot_location_exists? address
    return File.exist? address
  end

  def aka_directory_exists?
    return File.directory?("#{Dir.home}/.aka")
  end

  def showlast howmany=10
    if content = File.open(readYML("#{Dir.home}/.aka/.config")["location"]).read
      content.gsub!(/\r\n?/, "\n")
      content_array = content.split("\n")
      #why not just call the last five lines? Because i can't be sure that they are aliases
      total_aliases = []
      content_array.each_with_index { |line, index|
        value = line.split(" ")
        if value.length > 1 and value.first == "alias"
          total_aliases.push(line)
        end
      }
      puts ""
      if total_aliases.count > howmany
        total_aliases.last(howmany).each_with_index do |line, index|
          splitted= line.split('=')
          puts "#{total_aliases.count - howmany + index+1}. " + splitted[0] + "=" + splitted[1].red
        end
      else
        total_aliases.last(howmany).each_with_index do |line, index|
          splitted= line.split('=')
          puts "#{index+1}. " + splitted[0] + "=" + splitted[1].red
        end
      end
      puts ""
    end
  end

  def showUsage howmany=10, least=false
    value = reload_dot_file()
    #get all aliases
    if content = File.open(readYML("#{Dir.home}/.aka/.config")["history"]).read
      content.gsub!(/\r\n?/, "\n")
      content_array = content.split("\n")
      total_aliases = []
      content_array.each_with_index { |line, index|
        value = line.split(" ")
        total_aliases.push(value.first)
      }
      count_aliases(total_aliases, howmany, least)
    end
  end

  def count_aliases array, howmany, least=false
    name_array,count_array = [], []
    #find the unique value
    array.each_with_index { |value, index|
      if name_array.include?(value) == false
        name_array.push(value)
      end
    }
    #count the value
    name_array.each { |unique_value|
      count = 0
      array.each { |value|
        if (unique_value == value)
          count+=1
        end
      }
      count_array.push(count)
    }

    sorted_count_array, sorted_name_array = sort(count_array, name_array)

    #display the least used aliases
    if least == true
      if sorted_count_array.count == sorted_name_array.count
        puts ""
        sorted_name_array.last(howmany).each_with_index { |value, index|
          percent = ((sorted_count_array[sorted_name_array.last(howmany).size + index]).round(2)/array.size.round(2))*100
          str = "#{sorted_name_array.size-sorted_name_array.last(howmany).size+index+1}. #{value}"
          puts "#{str} #{showSpace(str)} #{showBar(percent)}"
        }
        puts ""
      else
        puts "something is wrong: count_array.count = #{sorted_count_array.count}\n
        name_array.count = #{sorted_name_array.count}. Please check your .bash_history.".pretty
      end
    else
      # #print out
      if sorted_count_array.count == sorted_name_array.count
        puts ""
        sorted_name_array.first(howmany).each_with_index { |value, index|
          percent = ((sorted_count_array[index]).round(2)/array.size.round(2))*100
          str = "#{index+1}. #{value}"
          puts "#{str} #{showSpace(str)} #{showBar(percent)}"
        }
        puts ""
      else
        puts "something is wrong: count_array.count = #{sorted_count_array.count}\n
              name_array.count = #{sorted_name_array.count}. Please check your .bash_history.".pretty
      end
    end
    puts "There's a total of #{array.size} lines in #{readYML("#{Dir.home}/.aka/.config")["history"]}."
  end

  def sort(countarray, namearray) #highest first. decscending.
    temp = 0, temp2 = ""
    countarray.each_with_index { |count, index|
      countarray[0..countarray.size-index].each_with_index { |x, thisindex|  #always one less than total

        if index < countarray.size-1 and thisindex < countarray.size-1
          if countarray[thisindex] < countarray[thisindex+1] #if this count is less than next count
            temp = countarray[thisindex]
            countarray[thisindex] = countarray[thisindex+1]
            countarray[thisindex+1] = temp

            temp2 = namearray[thisindex]
            namearray[thisindex] = namearray[thisindex+1]
            namearray[thisindex+1] = temp2
          end
        end

      }
    }#outer loop
    return countarray, namearray
  end

  def get_latest_history_file
    system("history -a")
  end

  def cleanup
    if content = File.open("#{readYML("#{Dir.home}/.aka/.config")["location"]}").read
      content.gsub!(/\r\n?/, "\n")
      content_array = content.split("\n")
      check = false
      while check == false
        check = true
        content_array.each_with_index { |line, index|
          if line == "" or line == "\n"
            content_array.delete_at(index)
            check = false
          end
        }
      end
      write_with_newline(content_array)
    end
  end

  ################################################
  ## Getting these babies ready for beauty contest
  ################################################

  class String
    def pretty
      return self.gsub("\s\t\r\f", ' ').squeeze(' ')
    end

    def is_i?
      !!(self =~ /\A[-+]?[0-9]+\z/)
    end
  end

  def showSpace word
    space = ""
    val = 20 - word.size
    val = 20 if val < 0
    val.times do
      space += " "
    end
    return space
  end

  def showBar percent
    result = ""
    val = percent/100 * 50
    val = 2 if val > 1 and val < 2
    val = 1 if val.round <= 1 #for visibiity, show two bars if it's just one
    val.round.times do
      result += "/"
    end
    return result + " #{percent.round(2)}%"
  end


  # command :config do |c|
  #   c.action do |args, options|
  #     # theyml = Hash.new
  #     # theyml["location"] = "~/.aka/.location"
  #     # theyml["global"] = "/Users/ytbryan/.bash_profile"
  #     # theyml["groups"] = "~/.aka/groups"
  #     # theyml["remote"] = "255, admin, 12.12.12.233"
  #     # theyml["path"] = "~/.aka"
  #     # writeYML("#{Dir.home}/.aka/.config", theyml)
  #     FileUtils.touch(readYML("#{Dir.home}/.aka/.config")["location"])
  #   end
  # end
  #
  # command :readconfig do |c|
  #   c.action do |args, options|
  #     puts "readYML('#{Dir.home}/.aka/.config')['location'] ->#{readYML("#{Dir.home}/.aka/.config")["location"].class} -> #{readYML("#{Dir.home}/.aka/.config")["location"]}"
  #     puts "readYML("#{Dir.home}/.aka/.config")["location"] -> #{ readYML("#{Dir.home}/.aka/.config")["location"].class} -> #{ readYML("#{Dir.home}/.aka/.config")["location"]}"
  #     puts "#{program(:path_to_location).class} -> #{program(:path_to_location)}"
  #   end
  # end
  #

  ###########################
  ### DEVELOPMENT
  ###########################

  # command :build do |c|
  #   c.syntax = 'aka build [options]'
  #   c.summary = 'build the VERSION file and run tests'
  #   c.action do |args, options|
  #     write(program(:version), './VERSION')
  #     puts "VERSION #{program(:version)} created at #{Time.now.strftime("%I:%M%p, %A, %d %b %Y")}"
  #   end
  # end

  # command :install do |c|
  #   c.syntax = 'aka copy [options]'
  #   c.summary = 'copy a local copy of aka to /usr/local/bin'
  #   c.action do |args, options|
  #     result = system("sudo cp aka /usr/local/bin")
  #     puts "Installed aka #{program(:version)} into /usr/local/bin (#{Time.now.strftime("%I:%M%p,%a,%d %b %Y")}).".red if result == true
  #     puts "" if result == true
  #   end
  # end
  #
  # command :uninstall do |c|
  #   c.syntax = 'aka uninstall [options]'
  #   c.summary = 'uninstall aka'
  #   c.action do |args, options|
  #     input = ask "Confirm that you want to uninstall aka? (y/N)"
  #     system("sudo rm -rf ~/.aka; sudo rm -rf /usr/local/bin/aka;") if input == "y"
  #   end
  # end

  def add_to_proj fullalias
    values = fullalias.split("=")
    yml = readYML("#{Dir.pwd}/.aka")
    puts yml
    if yml == false
      puts "nil"
      write_new_proj_aka_file fullalias
    else
      puts "not nil"
      yml["proj"]["title"] = "this is title"
      yml["proj"]["summary"] = "this is summary"
      yml["proj"]["aka"][values.first] = values[1]
      writeYML("#{Dir.pwd}/.aka", yml)
    end
  end
  #aka proj import
  #aka add aka="echo" -p
  #aka rm aka -p

  def write_new_proj_aka_file fullalias
    values = fullalias.split("=")

    theyml = {"proj" => {
                "title" => "",
                 "summary" => "",
                 "aliases" => {
                      "firstvalue" => ""
                            }}}
    # thirdyml = Hash.new
    # thirdyml["firstvalue"] = ""
    #
    # secondyml = Hash.new
    # secondyml["title"] = "this is title"
    # secondyml["summary"] = "this is title"
    # secondyml["aliases"] = thirdyml
    #
    # theyml = Hash.new
    # theyml["proj"] = secondyml

    writeYML("#{Dir.pwd}/.aka", theyml)
  end

  def createShortcut(proj)
    answer = ""
    proj["shortcuts"].to_a.each_with_index do |each,index|
      puts "hello there"
        answer += "#{each["name"]}
                    - #{each["command"]}
                    ".pretty
                    puts "hello wow"
        answer += "\n"
    end
    return answer
  end

  def add_last_command name
    command= find_last_command()
    return str = name + "=" + "#{command}"
  end

  def find_last_command
    #i think if you do history -w, you can retrieve the latest command
    if content = File.open(readYML("#{Dir.home}/.aka/.config")["history"]).read
      count=0
      content.gsub!(/\r\n?/, "\n")
      content_array = content.split("\n")
      # content_array.each_with_index { |line, index|
      #   puts "#{index} #{line}"
      # }

      return  content_array[content_array.count - 1]
    end
    #go through the history

    #take the last command

    #take the name

    #append together and save it
  end


  def parseARGS str
    array =  str.split(" ")
    array.each_with_index do |line, value|
      array[value] = line.gsub('#{pwd}', Shellwords.escape(Dir.pwd))
    end
    return array.join(" ")
  end

  def add_pwd_to_the_command
    #detect #{pwd}

    #get the pwd and replace the the pwd
  end


end

Aka.start(ARGV)
