require 'aka/version'
require 'aka/constants'
require 'aka/helpers'
require 'aka/printing'
require 'aka/core'
require 'aka/string'
require 'aka/config'
require 'aka/dependencies'

require 'yaml'
require 'shellwords'
require 'open-uri'

require_relative 'commands/destroy'
require_relative 'commands/edit'
require_relative 'commands/find'
require_relative 'commands/function'
require_relative 'commands/generate'
require_relative 'commands/init'
require_relative 'commands/list'
require_relative 'commands/proj'
require_relative 'commands/setup'
require_relative 'commands/usage'
